#!/bin/bash

# Quick Cashfree & Vercel Variables Check
echo "🔍 Checking Environment Variables..."
echo ""

echo "📋 Variables in your .env file:"
echo "CASHFREE_CLIENT_ID: $(grep CASHFREE_CLIENT_ID .env | cut -d '=' -f2 | cut -c1-8)..."
echo "CASHFREE_MODE: $(grep CASHFREE_MODE .env | cut -d '=' -f2)"
echo "NEXT_PUBLIC_BASE_URL: $(grep NEXT_PUBLIC_BASE_URL .env | cut -d '=' -f2)"
echo ""

echo "⚠️  IMPORTANT VERCEL CHECKS:"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your project"
echo "3. Settings → Environment Variables"
echo ""
echo "4. Verify these variables exist with EXACT names:"
echo "   ✓ CASHFREE_CLIENT_ID"
echo "   ✓ CASHFREE_CLIENT_SECRET"
echo "   ✓ CASHFREE_MODE"
echo "   ✓ NEXT_PUBLIC_BASE_URL"
echo ""
echo "5. Check the VALUES match your local .env:"
echo "   - CASHFREE_MODE should be: production"
echo "   - NEXT_PUBLIC_BASE_URL should be: https://www.pixelsdigital.tech"
echo ""
echo "6. Make sure they're enabled for: Production, Preview, Development"
echo ""

echo "📝 Common Mistakes:"
echo "   ❌ Variable name typo (CASHFREE_CLIENT_SECRET vs CASHFREE_SECRET_KEY)"
echo "   ❌ Extra spaces in values"
echo "   ❌ Using sandbox credentials with production mode"
echo "   ❌ Not enabled for 'Production' environment"
echo ""

echo "🔧 If Variables Are Missing/Wrong:"
echo "   1. Add/Fix them in Vercel Dashboard"
echo "   2. Redeploy: Deployments → Latest → ... → Redeploy"
echo "   3. Wait 2-3 minutes"
echo "   4. Try payment again"
echo "   5. Check Vercel Function Logs immediately"
echo ""

echo "🚨 MOST LIKELY ISSUE:"
echo "   Missing NEXT_PUBLIC_BASE_URL in Vercel"
echo "   → Add it: https://www.pixelsdigital.tech"
echo ""
