#!/bin/bash

# This script shows you ALL environment variables you need to add to Vercel
# It masks the sensitive values for security

echo "=========================================="
echo "📋 VERCEL ENVIRONMENT VARIABLES TO ADD"
echo "=========================================="
echo ""
echo "Copy these variable NAMES and their VALUES from your .env file"
echo "Then add them to: Vercel Dashboard → Settings → Environment Variables"
echo ""
echo "=========================================="
echo "🔵 AWS S3 (File Uploads)"
echo "=========================================="
echo ""
echo "✓ AWS_ACCESS_KEY_ID"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ AWS_SECRET_ACCESS_KEY"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ AWS_REGION"
echo "  Value: $(grep '^AWS_REGION=' .env 2>/dev/null | cut -d '=' -f 2 || echo 'ap-south-1')"
echo ""
echo "✓ S3_BUCKET_NAME"
echo "  Value: $(grep '^S3_BUCKET_NAME=' .env 2>/dev/null | cut -d '=' -f 2 || echo 'pixels-official')"
echo ""
echo "=========================================="
echo "📧 AWS SES SMTP (Email)"
echo "=========================================="
echo ""
echo "✓ SMTP_HOST"
echo "  Value: $(grep '^SMTP_HOST=' .env 2>/dev/null | cut -d '=' -f 2 || echo 'email-smtp.us-east-1.amazonaws.com')"
echo ""
echo "✓ SMTP_PORT"
echo "  Value: $(grep '^SMTP_PORT=' .env 2>/dev/null | cut -d '=' -f 2 || echo '587')"
echo ""
echo "✓ SMTP_USER"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ SMTP_PASSWORD"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ EMAIL_FROM"
echo "  Value: $(grep '^EMAIL_FROM=' .env 2>/dev/null | cut -d '=' -f 2 || echo 'noreply@pixelsdigital.tech')"
echo ""
echo "=========================================="
echo "🗄️ Database & Auth"
echo "=========================================="
echo ""
echo "✓ MONGODB_URI"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ JWT_SECRET"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ NEXTAUTH_SECRET"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ NEXTAUTH_URL (Production)"
echo "  Value: https://www.pixelsdigital.tech"
echo ""
echo "=========================================="
echo "💳 Cashfree"
echo "=========================================="
echo ""
echo "✓ CASHFREE_CLIENT_ID"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ CASHFREE_CLIENT_SECRET"
echo "  Value: (Copy from .env)"
echo ""
echo "✓ CASHFREE_MODE (Production)"
echo "  Value: production"
echo ""
echo "✓ NEXT_PUBLIC_CASHFREE_MODE (Production)"
echo "  Value: production"
echo ""
echo "=========================================="
echo "📝 Instructions"
echo "=========================================="
echo ""
echo "1. Open your .env file: cat .env"
echo "2. Go to: https://vercel.com/dashboard"
echo "3. Select your project → Settings → Environment Variables"
echo "4. Add each variable above"
echo "5. For each: Check ✓ Production ✓ Preview ✓ Development"
echo "6. Click Save"
echo "7. Redeploy your app"
echo ""
echo "Need help? See VERCEL_AWS_SETUP.md for detailed guide"
echo "=========================================="
