/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'case-studies': CaseStudy;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'test-home-page': TestHomePage;
    'services-page': ServicesPage;
    navbar: Navbar;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'test-home-page': TestHomePageSelect<false> | TestHomePageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  title: string;
  /**
   * Used for the URL (e.g., my-awesome-project)
   */
  slug: string;
  client: string;
  category?: string | null;
  /**
   * Large bold headline for the case study (e.g., "Helping legal teams get back to what matters.")
   */
  heroTitle: string;
  /**
   * List of services provided (e.g., Branding, Art Direction)
   */
  services?:
    | {
        service?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * This is the image that will appear in the grid on the Home Page and Portfolio page.
   */
  thumbnail: string | Media;
  brief?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Gallery for The Challenge section
   */
  gallery?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Gallery for The Solution section
   */
  solutionGallery?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy content field / Additional rich text
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoSection?: {
    /**
     * Toggle to show or hide the video section
     */
    showVideo?: boolean | null;
    heading?: string | null;
    /**
     * Direct URL to a video file (e.g. MP4 on S3 or external hosting). Not for YouTube links.
     */
    videoUrl?: string | null;
    /**
     * Or upload a video directly
     */
    videoMedia?: (string | null) | Media;
    /**
     * Optional thumbnail image for the video player
     */
    posterImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * The name of the service (e.g., Website Development)
   */
  title: string;
  /**
   * URL slug (e.g., website-development)
   */
  slug: string;
  /**
   * The name of the Lucide icon to use on the Index Hub card (e.g., Code, Search, BarChart, PenTool)
   */
  icon: string;
  /**
   * Short description for the Index Hub card
   */
  description: string;
  /**
   * Long description for the top of the Details Page
   */
  heroDescription?: string | null;
  /**
   * Quick stats for the right-hand card in Hero
   */
  howWeWork?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  whoThisIsFor?:
    | {
        title: string;
        description: string;
        color?: ('bg-purple-400' | 'bg-emerald-400' | 'bg-pink-300') | null;
        id?: string | null;
      }[]
    | null;
  whatWeHelpSolve?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The dark immersive card section
   */
  whyUs?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  builtForDelivery?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  coreCapabilities?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  deliverySteps?:
    | {
        stepNumber: string;
        title: string;
        description: string;
        /**
         * Small italicized text
         */
        highlight?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  techStack?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  relatedProjects?: (string | CaseStudy)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  category?: T;
  heroTitle?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  thumbnail?: T;
  brief?: T;
  challenge?: T;
  solution?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  solutionGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?: T;
  videoSection?:
    | T
    | {
        showVideo?: T;
        heading?: T;
        videoUrl?: T;
        videoMedia?: T;
        posterImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  description?: T;
  heroDescription?: T;
  howWeWork?:
    | T
    | {
        item?: T;
        id?: T;
      };
  whoThisIsFor?:
    | T
    | {
        title?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  whatWeHelpSolve?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whyUs?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  builtForDelivery?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  coreCapabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  deliverySteps?:
    | T
    | {
        stepNumber?: T;
        title?: T;
        description?: T;
        highlight?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    headingWord1: string;
    headingLine1Rest: string;
    headingLine2: string;
    headingLine3: string;
    subheading: string;
    heroImage?: (string | null) | Media;
  };
  brands?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  intro: {
    eyebrow: string;
    headingLine1: string;
    headingHighlight: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  solutions: {
    headingLine1: string;
    headingHighlight: string;
    cards?:
      | {
          /**
           * Use new lines (Enter) for line breaks.
           */
          title: string;
          description: string;
          theme: 'white' | 'yellow';
          id?: string | null;
        }[]
      | null;
  };
  aiAutomation: {
    headingLine1: string;
    headingHighlight: string;
    subheading: string;
    cards?:
      | {
          /**
           * Use new lines for line breaks.
           */
          title: string;
          description: string;
          theme: 'white' | 'dark';
          id?: string | null;
        }[]
      | null;
  };
  ourWork: {
    headingLine1: string;
    headingHighlight: string;
    /**
     * Select case studies to feature on the home page.
     */
    projects?: (string | CaseStudy)[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  heroHeadline1: string;
  heroHighlight: string;
  heroHeadline2: string;
  heroImage: string | Media;
  approachTitle1?: string | null;
  approachHighlight?: string | null;
  approachTitle2?: string | null;
  approachText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  differentTitle1?: string | null;
  differentHighlight?: string | null;
  differentCards?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        icon?: (string | null) | Media;
        color?: ('#d8b4fe' | '#6ee7b7' | '#f9a8d4' | '#fdba74') | null;
        id?: string | null;
      }[]
    | null;
  deliverTitle1?: string | null;
  deliverHighlight?: string | null;
  deliverCards?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        icon?: (string | null) | Media;
        color?: ('#d8b4fe' | '#6ee7b7' | '#f9a8d4' | '#fdba74') | null;
        id?: string | null;
      }[]
    | null;
  deliverWideCard?: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    icon?: (string | null) | Media;
    color?: ('#d8b4fe' | '#6ee7b7' | '#f9a8d4' | '#fdba74') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-home-page".
 */
export interface TestHomePage {
  id: string;
  heroPrefix?: string | null;
  heroRotatingAdjectives?:
    | {
        word?: string | null;
        id?: string | null;
      }[]
    | null;
  heroSuffix?: string | null;
  heroRotatingNouns?:
    | {
        word?: string | null;
        id?: string | null;
      }[]
    | null;
  heroVideo?: (string | null) | Media;
  introLabel?: string | null;
  introTitle?: string | null;
  introDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  servicesCards?:
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        backgroundColor?: ('#F2E8FF' | '#FFE3EE' | '#FFE6D9' | '#E3F8F8') | null;
        icon?: (string | null) | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  logosTitle?: string | null;
  logos?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: string;
  hero: {
    /**
     * Wrap text in *asterisks* to highlight it in purple (e.g. We are innovating *Exciting Solutions* for Campaigns)
     */
    title: string;
    subtitle: string;
    /**
     * Large hero image shown at the top of the page
     */
    heroImage?: (string | null) | Media;
  };
  /**
   * Categories to group services on the main Services Hub page
   */
  serviceCategories?:
    | {
        /**
         * e.g., Development & Technology
         */
        categoryName: string;
        /**
         * Select the services to display under this category
         */
        services: (string | Service)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Pricing plans displayed at the bottom of the page
   */
  pricingPlans?:
    | {
        name: string;
        price: number;
        duration?: string | null;
        description?: string | null;
        popular?: boolean | null;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: string;
  /**
   * Upload the logo for the navigation bar (transparent PNG recommended).
   */
  logo?: (string | null) | Media;
  /**
   * Navigation links displayed in the center of the navbar.
   */
  links?:
    | {
        label: string;
        /**
         * URL (e.g. /services or https://google.com)
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Call to action button settings.
   */
  ctaButton?: {
    /**
     * Toggle to show or hide the call-to-action button.
     */
    showButton?: boolean | null;
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headingWord1?: T;
        headingLine1Rest?: T;
        headingLine2?: T;
        headingLine3?: T;
        subheading?: T;
        heroImage?: T;
      };
  brands?:
    | T
    | {
        name?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        eyebrow?: T;
        headingLine1?: T;
        headingHighlight?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        headingLine1?: T;
        headingHighlight?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              theme?: T;
              id?: T;
            };
      };
  aiAutomation?:
    | T
    | {
        headingLine1?: T;
        headingHighlight?: T;
        subheading?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              theme?: T;
              id?: T;
            };
      };
  ourWork?:
    | T
    | {
        headingLine1?: T;
        headingHighlight?: T;
        projects?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroHeadline1?: T;
  heroHighlight?: T;
  heroHeadline2?: T;
  heroImage?: T;
  approachTitle1?: T;
  approachHighlight?: T;
  approachTitle2?: T;
  approachText?: T;
  differentTitle1?: T;
  differentHighlight?: T;
  differentCards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        color?: T;
        id?: T;
      };
  deliverTitle1?: T;
  deliverHighlight?: T;
  deliverCards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        color?: T;
        id?: T;
      };
  deliverWideCard?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        color?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-home-page_select".
 */
export interface TestHomePageSelect<T extends boolean = true> {
  heroPrefix?: T;
  heroRotatingAdjectives?:
    | T
    | {
        word?: T;
        id?: T;
      };
  heroSuffix?: T;
  heroRotatingNouns?:
    | T
    | {
        word?: T;
        id?: T;
      };
  heroVideo?: T;
  introLabel?: T;
  introTitle?: T;
  introDescription?: T;
  servicesCards?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundColor?: T;
        icon?: T;
        link?: T;
        id?: T;
      };
  logosTitle?: T;
  logos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        heroImage?: T;
      };
  serviceCategories?:
    | T
    | {
        categoryName?: T;
        services?: T;
        id?: T;
      };
  pricingPlans?:
    | T
    | {
        name?: T;
        price?: T;
        duration?: T;
        description?: T;
        popular?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        showButton?: T;
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}